### ISSUE TITLE
Add a Code of Conduct

### ISSUE THREAD

**Issue by surfinzap** [surfinzap/typopo-vscode#1]
Add CODE_OF_CONDUCT.md to a repo root.

Use these guidelines:
https://github.com/facebook/react/blob/master/CODE_OF_CONDUCT.md

Change project email to help@typopo.org

**Comment by surfinzap** [comment]
Thanks @a12baghel2 for your interest! Go ahead, take the issue and send me a PR when you’re done.

**Comment by a12baghel2** [comment]
#2  I've opened a PR please review.

**Comment by surfinzap** [comment]
Done by @a12baghel2 in #2, thanks for your help!
